export const NUM_MIN_ALTERADO = 'NUM_MIN_ALTERADO';
export const NUM_MAX_ALTERADO = 'NUM_MAX_ALTERADO';
export const API_ALTERADO = 'API_ALTERADO';
export const TOKEN_ALTERADO = 'TOKEN_ALTERADO';
export const CODE_ALTERADO = 'CODE_ALTERADO';
export const REFRESH_TOKEN_ALTERADO = 'REFRESH_TOKEN_ALTERADO';